Fix for excessive memory usage on mailboxes with thousands of folders
Alinto/sogo pull request #347
Opened 2023-10-11 19:03 UTC by leecher1337

https://bugs.sogo.nu/view.php?id=5884

2023-10-16 07:41 UTC, WoodySlum requested changes
Thank you for contributing to SOGo. It seems good to me except for the commit naming. I will fix it when merging.
Can you also replace it line https://github.com/Alinto/sogo/blob/e748cdc8fbde382917d2991663a8390d7c35ceae/ActiveSync/SOGoActiveSyncDispatcher%2BSync.m#L2640 ?
@tfux as you know EAS part well is it ok for you also ?

2023-10-16 07:41 UTC, WoodySlum commented on ActiveSync/SOGoActiveSyncDispatcher+Sync.m
> +      globalMetadata = [self globalMetadataForDevice];
Can you also use this variable L2640 ?

2023-10-17 07:35 UTC, leecher1337 commented on ActiveSync/SOGoActiveSyncDispatcher+Sync.m
> +      globalMetadata = [self globalMetadataForDevice];
Is it OK now?

2023-10-17 08:59 UTC, WoodySlum commented
Yes thank you very much. I'm just waiting for a feedback of @tfux, but the
fix seems for me



Le mar. 17 oct. 2023 à 09:35, leecher1337 ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In ActiveSync/SOGoActiveSyncDispatcher+Sync.m
> <https://github.com/Alinto/sogo/pull/347#discussion_r1361636003>:
>
> > @@ -2627,10 +2627,10 @@ - (void) processSync: (id <DOMElement>) theDocumentElement
>        // We first check of any of the collections we want to sync are already
>        // in an other sync process. If that's the case, we do not do anything
>        // and we return immediately. So we'll let the other sync process terminate
> +      globalMetadata = [self globalMetadataForDevice];
>
> Is it OK now?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Alinto/sogo/pull/347#discussion_r1361636003>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUTMZTGBLZPWOZ7FCBL2ETX7YYLNAVCNFSM6AAAAAA54OZ2NCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBRGU3DKOJWGA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-17 14:52 UTC, WoodySlum commented on ActiveSync/SOGoActiveSyncDispatcher+Sync.m
> +      globalMetadata = [self globalMetadataForDevice];
Nice thank you

2023-10-17 14:53 UTC, WoodySlum approved these changes

2023-10-17 18:34 UTC, tfux commented
Fix is ok. Good catch.

2023-10-17 19:03 UTC, WoodySlum commented
Thank you all !

2023-10-17 19:03 UTC, merged